### ISSUE TITLE
Excuse me. How do i use this?

### ISSUE THREAD

**Issue by shalola** [Elskom/Els_kom_new#174]
I tried so many times to compile this to no avail.
i gave up then use the legacy version instead..

but here s one thing. i dont know how you re supposed to use this program. i tried copying the .kom files i want to the bin folder. and press unpack. but nothing happen. so can you write a simple tutorial on how to use the program in the read.md many thanks.

**Comment by AraHaan** [comment]
I had one on youtube, basically the program should make a subfolder named ``koms`` and then you copy them there.

Also I have since rebranded the dependencies into a single metapackage, however it has not been pushed to nuget yet, so you would have to clone to the folder to where you cloned this into and then build that using the .NET SDK.

Also I recommend using the .NET 6 SDK from the https://github.com/dotnet/installer/ where on the readme it shows the installer for their "master" branch, this is because the preview1 for .NET 6 branch has a bug in which I reported, even though the one in the .NET 6 branch is newer.

This is because the .NET 5 SDK's that have stable releases has a bug where build would never work as it would not restore the nuget packages so then you would be forced to use the .NET 6 SDK's until VS2019 19.9 is released as stable.

Also there is a bug if you try to compile this using ``dotnet build`` and so would have to build this inside of Visual Studio due to the fact that for some reason the build fails even though it is targeting .NET Framework that it thinks I should reference ``System.Resources.Extensions`` for non-string resources even though those are built into System.Windows.Forms.dll on the .NET Framework.

Also I recommend using the .NET Framework build for now as there is a bug with the positions of the control buttons at the top of the settings form. I been looking into that issue for months.

**Comment by AraHaan** [comment]
So this is the steps in which to be able to build:

run the following commands:
- ``git clone https://github.com/Elskom/Sdk.git --recursive``
- ``cd Sdk``
- ``dotnet build --configuration Release`` (will restore packages needed to build the Sdk).
- ``dotnet pack --configuration Release --no-build``

And make sure the package outputs are added to your pc's global nuget.config and enabled.

Now run:
- `` cd ..`` (to leave the Sdk dir inside of whatever terminal you use (powershell or command prompt)
- ``cd Els_kom_new``
- ``dotnet build --configuration Release`` (will successfully build .NET 5, however it will not work for .NET Framework until you open the solution pcbuild.sln inside of Visual Studio 2019.

**Comment by AraHaan** [comment]
Also I plan to rename branch master to ``main`` as well and also to remove appveyor.

**Comment by AraHaan** [comment]
Also forgot to mention that the plugins to komv2 and komv3 (that implements packing and unpacking) are currently private at the moment so out of the box they won't be unpack or even packable until they go public again.

**Comment by shalola** [comment]
thanks for the generous reply. im really interested in the project. all other unpacker like QUICKBMS. Only have version 1 to 4. But in the description this program can unpack ver 5 which is the version of gc im playing. one thing, Is the header editable? like for example the one KOG makes have KOG... header but the private server that i played in has GCM... as the header.

**Comment by AraHaan** [comment]
Well it only supports the kow with KOG on the plugins for now, the GCM ones are the same, they just changed the KOG part to GCM last time I checked.

**Comment by AraHaan** [comment]
Also on the about form's code it points to an voidels forms topic on how to use the program too (which had the links to my videos on youtube on the how to use as well too), which has long since been gone 😭 and so the link in the about form been broken since void closure in 2019.

I guess what *should* be done is to open a wiki, however I sadly do not contain the contents of that forum topic or remember exactly what all it said before either which is also sad.

**Comment by AraHaan** [comment]
@shalola I would pull the changes from master, also will rename master too.

**Comment by shalola** [comment]
hello, yeah im really new to modding GC. and i did tried the legacy ones. sadly cant decrypt the GCM files.. either bcs of the header or the version of the encryption. gcm uses version 5.

![image](https://user-images.githubusercontent.com/37476685/108004519-60b45100-6ff6-11eb-968b-b6debf95b288.png)

Is it compile-able now? last time i tried it said this error in particular.

**Comment by AraHaan** [comment]
It should be able to be compiled, note: I am also working on a copy where the Sdk uses DependencyInjection to fully ensure that it only uses 1 instance of HttpClient for the entire application's lifetime (as if it did not it would be a bug that would exhaust all of the sockets related to the internet on windows which would not be good). The HttpClient however is only used by the plugin update checker which can then install plugin updates (or in some cases uninstall them).

I am also looking into being able to install and uninstall plugins and load/unload them when updated/installed/uninstalled too so that way the program would not need to be restarted as well.
