### ISSUE TITLE
Crashes when trying to unpack or repack

### ISSUE THREAD

**Issue by Squididly** [Elskom/Els_kom_new#45]
## Issue Description

After setting the path to my elsword folder it will give me an unhandled exception
if i just run the kom extractor by itself then it gives me this error
![image](https://user-images.githubusercontent.com/34932134/34431256-715dc1ae-ec22-11e7-89d8-2691463f5955.png)
and if i run the kom re-packer it gives me that error 
![image](https://user-images.githubusercontent.com/34932134/34435702-767958c0-ec44-11e7-9f6c-9985cee3348e.png)

# Debug information
- Els_kom version: ``1.4.9.8``
- OS: ``Windows 10 Pro Version 1607``
- OS Arch: ``x64``
- OS Build: ``14393.1944``

**Comment by AraHaan** [comment]
That is because of an issue with my import hook needing an ``base64`` module implemented in C, however because it uses ``PyBytes_FromObject`` to pass in an unicode object as bytes or w/e which depends on ``encodings`` which is why it crashes because it cant load the standard library from ``pythonXY.zip``.

**Comment by AraHaan** [comment]
Alright, how I got enough information on KOM V4 and will be implementing it in the next couple of days.

**Comment by AraHaan** [comment]
I think this was fixed.
