### ISSUE TITLE
Build errors Win 10

### ISSUE THREAD

**Issue by BLMTuan** [Elskom/Els_kom_new#48]
## Issue Description

![untitled](https://user-images.githubusercontent.com/35293841/34767695-513b8a6a-f62b-11e7-99e2-6ddc8a1d7a37.png)

I followed all the steps but still cant build it right

# Debug information
- Els_kom version: ``[1.4.9.8]``
- OS: ``[win 10 Home]``
- OS Arch: ``[Your OS Arch here]``
- OS Build: ``[Your OS Build here]``

Note: Newer versions from time to time ship with a newer version of python embedded.

**Comment by BLMTuan** [comment]
' ')?

**Comment by Squididly** [comment]
I also got the same error but what I did was instead of running the build.bat i opened the pcbuild.sln and built it from there 
![image](https://user-images.githubusercontent.com/34932134/34901099-d38f8a94-f7ba-11e7-9f35-4959c17d9884.png)
then you would build the kom extractor

**Comment by Squididly** [comment]
however i recommend just using these in the meanwhile 
[kom.tools](https://github.com/Elskom/Els_kom_new/files/1593784/kom.tools.zip)

**Comment by AraHaan** [comment]
I recommend tryong the kom-rework branch, however that branch is sadly not complete yet, and seems to crash on zlib when decompressing as an stream and not an file... :thinking:

**Comment by AraHaan** [comment]
Alright I just pulled some updates to things like an start to an autogenerated changelog and an update to the templates on github to hopefully make it much easier to manage. I will update the code and actually full in the changelog entry items as soon as I can and finush up the reimplementation. After that I hope all would be ok.

**Comment by AraHaan** [comment]
@BLMTuan, @Squididly due to issues with my laptop that has some uncommited changes to the core that implements kom v2, v3, and v4 (with some local fixes to fix an v3 and v4 crash with zlib) however combine that woth an entry overflow with kom b2 I got no idea how I can fix the entry count for v2 for it to work like the python v2 implementation. 🤔 However I am trying and my laptop is the reason why I put issue #47 on hold for now. Also after some thoughts the plan for 1.5.0.0 has changed from implement algorithm 2 and 3 support to providing algorithm 2 and 3 support via 3rd party plugins. However loading and invoking them might be an challenge. I think since I hopefully can get zlib built into the core working right to basically have the plugins only do the per kom encryption/decryption with the function taking in the file stream and the name of the folder that is being packed to identify the kom that is being packed for the proper encryption keys. Also knowing that is based on file extensions in the unpacked kom target folder that can be hard coded into the core that would theb invoke the proper encryption / decryption.

**Comment by AraHaan** [comment]
Pushed the kom-rework branch to master, however some of the kom plugins might look to be incomplete because they are. This was because I had to get rid of the old python stuff as soon as possible. Also I plan merging the legacy repository into a legacy branch which would be an orphan branch having no commits from master. Also seems that building only works in clones for now.
